-- MySQL Script generated by MySQL Workbench
-- Thu Feb  3 18:59:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ESPs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESPs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GPSData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GPSData` (
  `GPS_ESP_id` INT NOT NULL,
  `GPS_DateTimeFromESP` DATETIME NOT NULL,
  `GPS_TimestampAdded` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `GPS_long` DECIMAL(9,6) NOT NULL,
  `GPS_lat` DECIMAL(8,6) NOT NULL,
  PRIMARY KEY (`GPS_ESP_id`, `GPS_DateTimeFromESP`),
  CONSTRAINT `fk_GPSData_ESPs`
    FOREIGN KEY (`GPS_ESP_id`)
    REFERENCES `mydb`.`ESPs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TempData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TempData` (
  `Temp_ESP_id` INT NOT NULL,
  `Temp_DateTimeFromESP` DATETIME NOT NULL,
  `Temp_TimestampAdded` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Temp_Temp` DECIMAL(3,1) NOT NULL,
  PRIMARY KEY (`Temp_ESP_id`, `Temp_DateTimeFromESP`),
  CONSTRAINT `fk_TempData_ESPs`
    FOREIGN KEY (`Temp_ESP_id`)
    REFERENCES `mydb`.`ESPs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LightIntensityData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LightIntensityData` (
  `Light_ESP_id` INT NOT NULL,
  `Light_DateTimeFromESP` DATETIME NOT NULL,
  `Light_TimestampAdded` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Light_intensity` SMALLINT(0) NOT NULL,
  PRIMARY KEY (`Light_ESP_id`, `Light_DateTimeFromESP`),
  CONSTRAINT `fk_LightIntensityData_ESPs`
    FOREIGN KEY (`Light_ESP_id`)
    REFERENCES `mydb`.`ESPs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
